### ISSUE TITLE
How to add default wallpapers

### ISSUE THREAD

**Issue by joel3084** [rahulshah456/ParallaxSlideshowLiveWallpaper#1]
I want to add some default wallpaper that will ship with the app. Can you please tell me how this can be done?

**Comment by rahulshah456** [comment]
@joel3084  You can initially add some default wallpapers when the database is created for the first time or opened if already created through a callback in LiveWallpaperDatabase class

```
if (INSTANCE == null) {
                    INSTANCE = Room.databaseBuilder(context.getApplicationContext(),
                          LiveWallpaperDatabase.class, DB_NAME)
                                         .addCallback(callback)
                                         .build();

                }
```

This is the sample callback where you can add you default wallpapers

```
RoomDatabase.Callback callback = new RoomDatabase.Callback() {
    public void onCreate (SupportSQLiteDatabase db) {
        // add,delete,update your initial wallpapers 
    }
    public void onOpen (SupportSQLiteDatabase db) {
         // do anything
    }
};

```

**Comment by joel3084** [comment]
Thanks a lot for replying back. I've been learning Android App Development for couple of months as a hobby. I wanted to try something new out.

I edited couple of android app source code but your code seem pretty complex to me. I can't figure out how to use it, sorry.

It would be really helpful if you could give me an example how to use it. Suppose I want to add this [https://cdn.pixabay.com/photo/2015/11/07/11/24/northern-lights-1031101_960_720.jpg](https://cdn.pixabay.com/photo/2015/11/07/11/24/northern-lights-1031101_960_720.jpg) picture.

Thanks again for precious time.
